<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc5718fb700b08c830e01fcb697879ec6
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LINE\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LINE\\' => 
        array (
            0 => __DIR__ . '/..' . '/linecorp/line-bot-sdk/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc5718fb700b08c830e01fcb697879ec6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc5718fb700b08c830e01fcb697879ec6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc5718fb700b08c830e01fcb697879ec6::$classMap;

        }, null, ClassLoader::class);
    }
}
